name: Execute Jupyter Notebook

on:
  push:
    branches:
      - main

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.9  # Substitua '3.x' pela versão do Python que você está usando

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install notebook

      - name: Execute Jupyter Notebook
        run: |
          pip install nbconvert
          jupyter nbconvert --to notebook --execute --inplace your_notebook.ipynb
